export const Data_Leetspeak = [
  ["A", ["4", "@", "/\\", "/-\\", "?", "^", "α", "λ"]],
  ["B", ["8", "|3", "ß", "l³", "13", "I3", "J3"]],
  ["C", ["(", "[", "<", "©", "¢"]],
  ["D", ["D", "|)", "|]", "Ð", "đ", "1)"]],
  ["E", ["3", "€", "&", "£", "ε"]],
  ["F", ["F", "|=", "PH", "|*|-|", '|"', "ƒ", "l²"]],
  ["G", ["6", "&", "9"]],
  ["H", ["4", "#", "|-|", "}{", "]-[", "/-/", ")-("]],
  ["I", ["1", "!", "|", "][", "ỉ"]],
  ["J", ["J", "_|", "¿"]],
  ["K", ["K", "|<", "|{", "|(", "X"]],
  ["L", ["1", "|_", "£", "|", "][_"]],
  ["M", ["M", "/\\/\\", "/v\\", "|V|", "]V[", "|\\/|", "AA", "[]V[]", "|11", "/|\\", "^^", "(V)", "|Y|", "!\\/!"]],
  ["N", ["/V", "|\\|", "/\\/", "|V", "/\\\\/", "|1", "2", "?", "(\\)", "11", "r", "!\\!"]],
  ["O", ["0", "9", "()", "[]", "*", "°", "<>", "ø", "{[]}"]],
  ["P", ["9", "|°", "p", "|>", "|*", "[]D", "][D", "|²", "|?", "|D"]],
  ["Q", ["0_", "0,"]],
  ["R", ["2", "1²", "®", "?", "я", "12", ".-"]],
  ["S", ["5", "$", "§", "?", "ŝ", "ş"]],
  ["T", ["7", "+", "†", "']['", "|"]],
  ["U", ["U", "|_|", "µ", "[_]", "v"]],
  ["V", ["V", "\\/", "|/", "\\|", "\\'"]],
  ["W", ["W", "\\/\\/", "VV", "\\A/", "\\\\'", "uu", "\\^/", "\\|/", "uJ"]],
  ["X", ["X", "<", ")(", "}{", "%", "?", "×", "]["]],
  ["Y", ["Y", "`/", "°/", "¥"]],
  ["Z", ["2", "z", '"/_']],
  ["Ä", ["43", "°A°"]],
  ["Ö", ["03", "°O°"]],
  ["Ü", ["|_|3", "°U°"]],
  ["!", ["1", "!"]],
];

export const Data_Botanicals = [
  {
    plant: "Anis",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Erkältungs-Beschwerden", "Stoffwechsel-Probleme", "Blähungen", "Magen-Beschwerden"],
    effect: ["Entgiftend", "Appetitanregend", "Blähungstreibend"],
  },
  {
    plant: "Augentrost",
    "Botanische Familie": "Rachenblütler",
    discomfort: ["Augenentzündung"],
  },
  {
    plant: "Bärentraube",
    "Botanische Familie": "Heidekrautgewächse",
    discomfort: ["Nieren-Beschwerden"],
    effect: ["Entwässernd"],
  },
  {
    plant: "Bärlauch",
    "Botanische Familie": "Liliengewächse",
    discomfort: ["Blähungen", "Bluthochdruck", "Blutniederdruck", "Blutreinigung", "Gefäßreinigend", "Magen-Beschwerden", "Immunsystemkräftigend", "Gicht- / Rheumabeschwerden", "Verdauungs-Probleme"],
    effect: ["Appetitanregend", "Blutreinigend", "Blutdrucksenkend", "Blähungstreibend", "Cholesterinsenkend", "Darmfloraaufbauend", "Entgiftend", "Stoffwechselanregend", "Verdauungsfördernd"],
  },
  {
    plant: "Bärwurz",
    "Botanische Familie": "Doldenblütler",
    discomfort: ["Blähungen", "Stoffwechsel-Beschwerden"],
    effect: ["Blutreinigend"],
  },
  {
    plant: "Baldrian",
    "Botanische Familie": "Baldriangewächse",
    discomfort: ["Magen-Beschwerden", "Schlaf-Beschwerden"],
    effect: ["Beruhigend", "Entspannend", "Nervensystemstärkend"],
  },
  {
    plant: "Basilikum",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Durchfall-Erkrankung", "Stoffwechsel-Beschwerden", "Verdauungs-Beschwerden", "Blähungen"],
    effect: ["Appetitanregend", "Ballaststoffreich", "Entgiftend", "Appetitanregend"],
  },
  {
    plant: "Beifuß",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Verdauungs-Beschwerden"],
  },
  {
    plant: "Beinwell",
    "Botanische Familie": "Raublattgewächse",
    discomfort: ["Magen-Beschwerden", "Stoffwechsel-Beschwerden", "Haut-Probleme", "Gelenk-Beschwerden"],
    effect: ["Blutreinigend"],
  },
  {
    plant: "Bergamotte",
    "Botanische Familie": "Rautengewächse",
    discomfort: ["Erkältungs-Beschwerden"],
    effect: ["Appetitanregend"],
  },
  {
    plant: "Birke",
    "Botanische Familie": "Birkengewächse",
    discomfort: ["Gelenk-Beschwerden", "Stoffwechsel-Beschwerden", "Blasen- / Harnwegsbeschwerden"],
    effect: ["Blutreinigend", "Entgiftend", "Entwässernd"],
  },
  {
    plant: "Bockshornklee",
    "Botanische Familie": "Schmetterlingsblütler",
    discomfort: ["Verdauungs-Beschwerden", "Haut-Probleme", "Blähungen", "Bluthochdruck", "Blutniederdruck"],
    effect: ["Appetitanregend", "Ballaststoffreich", "Blut-/Gefäßreinigend", "Erkältungshemmend", "Entgiftend", "Immunsystemkräftigend"],
  },
  {
    plant: "Bohnenkraut",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Gicht- / Rheumabeschwerden", "Überreaktion des Immunsystems"],
    effect: ["Appetitanregend"],
  },
  {
    plant: "Boretsch",
    "Botanische Familie": "Boretschgewächse",
    discomfort: ["Magen-Beschwerden", "Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Ballaststoffreich", "Blutreinigend", "Entwässernd"],
  },
  {
    plant: "Brennessel",
    "Botanische Familie": "Nesselgewächse",
    discomfort: ["Magen-Beschwerden", "Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Blutreinigend", "Entwässernd"],
  },
  {
    plant: "Brunnenkresse",
    "Botanische Familie": "Kohlgewächse",
    discomfort: ["Magen-Beschwerden", "Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Entwässernd", "Appetitanregend", "Blutreinigend"],
  },
  {
    plant: "Cayennepfeffer",
    "Botanische Familie": "Nachtschattengewächse",
    discomfort: ["Leber- / Galle-Beschwerden", "Magen-Beschwerden", "Blähungen", "Verdauungs-Probleme"],
    effect: ["Verdauungsfördernd", "Appetitanregend"],
  },
  {
    plant: "Chilli",
    "Botanische Familie": "Nachtschattengewächse",
    discomfort: ["Magen-Beschwerden", "Blähungen"],
    effect: ["Appetitanregend"],
  },
  {
    plant: "Curry",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Blähungen", "Verdauungs-Probleme"],
    effect: ["Appetitanregend", "Blähungstreibend"],
  },
  {
    plant: "Dill",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Blähungen", "Magen-Beschwerden", "Stoffwechsel-Beschwerden"],
  },
  {
    plant: "Dreiblatt",
    "Botanische Familie": "Binsengewächse",
    discomfort: ["Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Entwässernd", "Entsäuernd", "Entgiftend"],
  },
  {
    plant: "Echinacea",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Erkältungskrankheiten"],
    effect: ["Immunsystemkräftigend"],
  },
  {
    plant: "Ehrenpreis",
    "Botanische Familie": "Rachenblütler",
    discomfort: ["Asthma-Beschwerden", "Stoffwechsel-Probleme"],
  },
  {
    plant: "Eibisch",
    "Botanische Familie": "Malvengewächse",
    discomfort: ["Erkältungs-Beschwerden", "Stoffwechsel-Beschwerden", "Magen-Beschwerden"],
    effect: ["Auswurffördernd"],
  },
  {
    plant: "Enzian",
    "Botanische Familie": "Enziangewächse",
    discomfort: ["Magen-Beschwerden", "Blähungen", "Leber- / Galle-Beschwerden", "Verdauungs-Probleme"],
    effect: ["Appetitanregend", "Immunsystemkräftigend"],
  },
  {
    plant: "Estragon",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Magen-Beschwerden"],
    effect: ["Immunsystemkräftigend", "Appetitanregend", "Verdauungsfördernd"],
  },
  {
    plant: "Fenchel",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Blähungen", "Magen-Beschwerden", "Erkältungs-Beschwerden", "Stoffwechsel-Beschwerden", "Durchfall-Erkrankung"],
    effect: ["Blutreinigend", "Blutdrucksenkend", "Entwässernd", "Appetitanregend"],
  },
  {
    plant: "Frauenmantel",
    "Botanische Familie": "Rosengewächse",
    discomfort: ["Blasen- / Harnwegsbeschwerden", "Frauenleiden"],
  },
  {
    plant: "Giersch",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Magen-Beschwerden", "Gicht- / Rheumabeschwerden"],
    effect: ["Entwässernd"],
  },
  {
    plant: "Ginseng",
    "Botanische Familie": "Aralyengewächse",
    discomfort: ["Alterserscheinungen"],
  },
  {
    plant: "Grüner Tee",
    "Botanische Familie": "Teestrauchgewächse",
    discomfort: ["Stoffwechsel-Probleme"],
    effect: ["Immunsystemkräftigend", "Blutreinigend", "Entgiftend", "Gefäßreinigend", "Stoffwechselanregend"],
  },
  {
    plant: "Hafer grün",
    "Botanische Familie": "Süßgräser",
    discomfort: ["Blasen- / Harnwegsbeschwerden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Beschwerden", "Gelenk-Beschwerden", "Nieren-Beschwerden"],
    effect: ["Gefäßreinigend", "Blutreinigend"],
  },
  {
    plant: "Heidelbeere",
    "Botanische Familie": "Heidekrautgewächse",
    discomfort: ["Durchfall-Erkrankung", "Blähungen", "Magen-Beschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Immunsystemkräftigend"],
  },
  {
    plant: "Hirtentäschel",
    "Botanische Familie": "Kohlgewächse",
    discomfort: ["Magen-Beschwerden", "Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Blutreinigend", "Entwässernd", "Appetitanregend", "Blutreinigend"],
  },
  {
    plant: "Holunder",
    "Botanische Familie": "Geißblattgewächse",
    discomfort: ["Stoffwechsel-Beschwerden", "Fieber", "Erkältungs-Beschwerden"],
    effect: ["Immunsystemkräftigend", "Appetitanregend", "Entgiftend"],
  },
  {
    plant: "Hopfen",
    "Botanische Familie": "Maulbeergewächse",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Schlafprobleme"],
    effect: ["Beruhigend"],
  },
  {
    plant: "Ingwer",
    "Botanische Familie": "Ingwergewächse",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Blähungen", "Erkältungs-Beschwerden"],
    effect: ["Appetitanregend", "Blähungstreibend", "Entgiftend", "Darmfloraaufbauend"],
  },
  {
    plant: "Isländisches Moos",
    "Botanische Familie": "Laubflechten",
    discomfort: ["Erkältungs-Beschwerden", "Reizhusten"],
  },
  {
    plant: "Johanniskraut",
    "Botanische Familie": "Johanniskrautgewächse",
    discomfort: ["Leber- / Galle-Beschwerden", "Stoffwechsel-Beschwerden", "Frauenleiden", "Magen-Beschwerden", "Gelenk-Beschwerden", "Haut-Probleme"],
    effect: ["Nervensystemstärkend", "Immunsystemkräftigend"],
  },
  {
    plant: "Kalmus",
    "Botanische Familie": "Arongewächse",
    discomfort: ["Magen-Beschwerden", "Blähungen", "Verdauungs-Probleme"],
    effect: ["Immunsystemkräftigend"],
  },
  {
    plant: "Kamille",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Blähungen", "Frauenleiden", "Haut-Probleme", "Magen-Beschwerden", "Stoffwechsel-Beschwerden", "Zahnfleischentzündung", "Schlaf-Beschwerden", "Blasen- / Harnwegsbeschwerden"],
    effect: ["Krampflösend"],
  },
  {
    plant: "Kapern",
    "Botanische Familie": "Kaperngewächse",
    discomfort: ["Magen-Beschwerden", "Blasen- / Harnwegsbeschwerden", "Erkältungs-Beschwerden"],
    effect: ["Entwässernd"],
  },
  {
    plant: "Kapuzinerkresse",
    "Botanische Familie": "Kapuzinerkressengewächse",
    discomfort: ["Magen-Beschwerden", "Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Appetitanregend", "Blutreinigend", "Entwässernd"],
  },
  {
    plant: "Kardamom",
    "Botanische Familie": "Ingwergewächse",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Blähungen"],
    effect: ["Appetitanregend"],
  },
  {
    plant: "Karotte",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Magen-Beschwerden", "Stoffwechsel-Beschwerden", "Durchfall-Erkrankung"],
    effect: ["Appetitanregend", "Entgiftend"],
  },
  {
    plant: "Kerbel",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Blähungen", "Magen-Beschwerden", "Stoffwechsel-Probleme"],
  },
  {
    plant: "Knoblauch",
    "Botanische Familie": "Liliengewächse",
    discomfort: ["Bluthochdruck", "Immunsystemschwäche"],
    effect: ["Immunsystemkräftigend", "Blut- / Gefäßreinigend", "Blähungstreibend", "Darmfloraaufbauend", "Cholesterinsenkend", "Entgiftend", "Verdauungsfördernd"],
  },
  {
    plant: "Koriander",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Magen-Beschwerden", "Blähungen", "Verdauungs-Probleme"],
    effect: ["Darmfloraaufbauend", "Blähungstreibend", "Verdauungsfördernd"],
  },
  {
    plant: "Kresse",
    "Botanische Familie": "Kreuzblütler",
    discomfort: ["Blähungen", "Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Stoffwechsel-Beschwerden", "Blutreinigung", "Erkältungs-Beschwerden"],
    effect: ["Entwässernd"],
  },
  {
    plant: "Kreuzkümmel",
    "Botanische Familie": "Doldenblütler",
    discomfort: ["Erkältungs-Beschwerden", "Menstruationsbeschwerden", "Blähungen", "Völlegefühl"],
    effect: ["Blähungstreibend", "Appetitanregend"],
  },
  {
    plant: "Kümmel",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Leber- / Galle-Beschwerden", "Verdauungs-Beschwerden", "Stoffwechsel-Beschwerden", "Blähungen"],
    effect: ["Immunsystemkräftigend"],
  },
  {
    plant: "Kurkuma",
    "Botanische Familie": "Ingwergewächse",
    discomfort: ["Magen-Beschwerden", "Herzbeschwerden"],
    effect: ["Blähungstreibend", "Stoffwechselanregend", "Appetitanregend"],
  },
  {
    plant: "Lapacho",
    "Botanische Familie": "Trompetenbaumgewächse",
    discomfort: ["Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden", "Blähungen", "Frauenleiden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Beschwerden", "Verdauungs-Beschwerden"],
    effect: ["Entwässernd", "Entsäuernd", "Entgiftend", "Blutreinigend", "Immunsystemkräftigend"],
  },
  {
    plant: "Lauch",
    "Botanische Familie": "Allioideae",
    discomfort: ["Leber- / Galle-Beschwerden", "Magen-Beschwerden", "Durchfall-Erkrankung"],
  },
  {
    plant: "Lavendel",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Haut-Probleme", "Frauenleiden", "Blähungen", "Magen-Beschwerden", "Gicht- / Rheumabeschwerden", "Schlafprobleme"],
    effect: ["Nervensystemstärkend", "Beruhigend"],
  },
  {
    plant: "Liebstöckel",
    "Botanische Familie": "Doldenblütler",
    discomfort: ["Magen-Beschwerden", "Stoffwechsel-Beschwerden", "Blutreinigung", "Blähungen", "Nieren-Beschwerden"],
    effect: ["Entgiftend", "Verdauungsfördernd", "Entwässernd"],
  },
  {
    plant: "Lindenblüte",
    "Botanische Familie": "Lindengewächse",
    discomfort: ["Fieber"],
    effect: ["Schweißtreibend"],
  },
  {
    plant: "Löwenzahn",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Blähungen"],
    effect: ["Entsäuernd", "Blutreinigend", "Entwässernd"],
  },
  {
    plant: "Lorbeer",
    "Botanische Familie": "Lorbeergewächse",
    discomfort: ["Stoffwechsel-Beschwerden", "Magen-Beschwerden"],
    effect: ["Immunsystemkräftigend"],
  },
  {
    plant: "Lungenkraut",
    "Botanische Familie": "Boretschgewächse",
    discomfort: ["Erkältungs-Beschwerden"],
    effect: ["Auswurffördernd"],
  },
  {
    plant: "Majoran",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Erkältungs-Beschwerden", "Blähungen"],
    effect: ["Blähungstreibend", "Appetitanregend", "Immunsystemkräftigend", "Verdauungsfördernd"],
  },
  {
    plant: "Meerettich",
    "Botanische Familie": "Kohlgewächse",
    discomfort: ["Nieren-Beschwerden", "Erkältungs-Beschwerden", "Stoffwechsel-Beschwerden", "Verdauungs-Beschwerden", "Magen-Beschwerden", "Gicht- / Rheumabeschwerden"],
    effect: ["Verdauungsfördernd", "Entgiftend", "Appetitanregend", "Immunsystemkräftigend"],
  },
  {
    plant: "Melisse",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Schlaf-Beschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Nervensystemstärkend", "Beruhigend"],
  },
  {
    plant: "Minze",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Magen-Beschwerden", "Blähungen", "Leber- / Gallebeschwerden"],
    effect: ["Immunsystemkräftigend"],
  },
  {
    plant: "Mistel",
    "Botanische Familie": "Mistelgewächse",
    discomfort: ["Bluthochdruck"],
    effect: ["Herzkräftigend", "Blutdrucksenkend", "Gefäßreinigend"],
  },
  {
    plant: "Muskat Nuß",
    "Botanische Familie": "Myrtengewächse",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Stoffwechsel-Probleme"],
  },
  {
    plant: "Muskateller Salbei",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Stoffwechsel-Beschwerden", "Magen-Beschwerden", "Mund- / Zahn-Hygiene", "Blasen- / Harnwegsbeschwerden", "Frauenleiden"],
    effect: ["Immunsystemkräftigend", "Schweißhemmend"],
  },
  {
    plant: "Odermenning",
    "Botanische Familie": "Rosengewächse",
    discomfort: ["Magen-Beschwerden", "Leber- / Gallebeschwerden"],
    effect: ["Ballaststoffreich"],
  },
  {
    plant: "Oregano",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Erkältungs-Beschwerden", "Blähungen"],
    effect: ["Appetitanregend", "Ballaststoffreich"],
  },
  {
    plant: "Paprika",
    "Botanische Familie": "Nachtschattengewächse",
    discomfort: ["Leber- / Galle-Beschwerden", "Magen-Beschwerden", "Blähungen", "Verdauungs-Probleme"],
    effect: ["Verdauungsfördernd", "Appetitanregend"],
  },
  {
    plant: "Petersilie",
    "Botanische Familie": "Doldengewächse",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Stoffwechsel-Beschwerden", "Durchfall-Erkrankung", "Blähungen", "Blasen- / Harnwegsbeschwerden", "Gelenk-Beschwerden", "Nieren-Beschwerden"],
    effect: ["Entwässernd", "Blutdrucksenkend"],
  },
  {
    plant: "Pfeffer",
    "Botanische Familie": "Pfeffergewächse",
    discomfort: ["Leber- / Galle-Beschwerden", "Verdauungs-Beschwerden", "Magen-Beschwerden", "Blähungen"],
    effect: ["Appetitanregend"],
  },
  {
    plant: "Pfefferminze",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Magen-Beschwerden", "Blähungen", "Leber- / Galle-Beschwerden", "Erkältungs-Beschwerden", "Durchfall-Erkrankung"],
    effect: ["Immunsystemkräftigend"],
  },
  {
    plant: "Piment",
    "Botanische Familie": "Myrtengewächse",
    discomfort: ["Magen-Beschwerden", "Stoffwechsel-Beschwerden", "Verdauungs-Probleme"],
    effect: ["Entgiftend", "Appetitanregend", "Darmfloraaufbauend"],
  },
  {
    plant: "Preiselbeere",
    "Botanische Familie": "Heidekrautgewächse",
    discomfort: ["Durchfall-Erkrankung", "Blähungen", "Magen-Beschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Blähungshemmend", "Immunsystemkräftigend"],
  },
  {
    plant: "Pu-Erh Tee",
    "Botanische Familie": "Teestrauchgewächse",
    discomfort: ["Durchfall-Erkrankung", "Stoffwechsel-Probleme"],
    effect: ["Immunsystemkräftigend", "Gefäßreinigend", "Stoffwechselanregend"],
  },
  {
    plant: "Ringelblume",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Haut-Probleme"],
    effect: ["Entzündungshemmend"],
  },
  {
    plant: "Rooibusch",
    "Botanische Familie": "Rotbuschgewächse",
    discomfort: ["Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden"],
    effect: ["Entwässernd", "Immunsystemkräftigend", "Anregend"],
  },
  {
    plant: "Rosenpaprika",
    "Botanische Familie": "Nachtschattengewächse",
    discomfort: ["Leber- / Galle-Beschwerden", "Magen-Beschwerden", "Blähungen", "Verdauungs-Probleme"],
    effect: ["Verdauungsfördernd", "Appetitanregend"],
  },
  {
    plant: "Rosmarin",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Blutniederdruck", "Verdauungs-Beschwerden", "Leber- / Galle-Beschwerden"],
    effect: ["Anregend", "Nervensystemstärkend", "Durchblutungsfördernd", "Immunsystemkräftigend"],
  },
  {
    plant: "Safran",
    "Botanische Familie": "Schwertliliengewächse",
    discomfort: ["Muskelschwäche", "Magenträgheit", "Lichtempfindlichkeit", "Konzentrationsschwäche", "Haut-Probleme", "Magen-Beschwerden"],
  },
  {
    plant: "Salbei",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Erkältungs-Beschwerden", "Stoffwechsel-Beschwerden", "Haut-Probleme", "Magen-Beschwerden", "Mund- / Zahn-Hygiene", "Blähungen", "Blasen- / Harnwegsbeschwerden", "Frauenleiden"],
    effect: ["Schweißhemmend", "Auswurffördernd", "Immunsystemkräftigend"],
  },
  {
    plant: "Sauerampfer",
    "Botanische Familie": "Knöterichgewächse",
    discomfort: ["Stoffwechsel-Beschwerden", "Magen-Beschwerden", "Blasen- / Harnwegsbeschwerden", "Blähungen"],
    effect: ["Immunsystemkräftigend", "Schweißhemmend", "Appetitanregend", "Blutreinigend"],
  },
  {
    plant: "Schafgarbe",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Gelenk-Beschwerden", "Stoffwechsel-Beschwerden", "Frauenleiden"],
    effect: ["Blutreinigend", "Entwässernd", "Entgiftend"],
  },
  {
    plant: "Schnittlauch",
    "Botanische Familie": "Liliengewächse",
    discomfort: ["Stoffwechsel-Beschwerden", "Blasen- / Harnwegsbeschwerden"],
  },
  {
    plant: "Schöllkraut",
    "Botanische Familie": "Mohngewächse",
    discomfort: ["Haut-Probleme"],
  },
  {
    plant: "Schwarzkümmel",
    "Botanische Familie": "Hahnenfußgewächse",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Blähungen", "Gelenk-Beschwerden", "Frauenleiden", "Erkältungs-Beschwerden", "Haut-Probleme", "Stoffwechsel-Beschwerden", "Verdauungs-Beschwerden", "Gicht- / Rheumabeschwerden", "Asthma-Beschwerden"],
    effect: ["Blähungstreibend", "Verdauungsfördernd", "Auswurffördernd", "Atemprobleme", "Immunsystemkräftigend"],
  },
  {
    plant: "Senf",
    "Botanische Familie": "Kohlgewächse",
    discomfort: ["Leber- / Galle-Beschwerden", "Magen-Beschwerden", "Blähungen", "Stoffwechsel-Probleme"],
    effect: ["Blähungstreibend", "Verdauungsfördernd", "Entgiftend", "Immunsystemkräftigend", "Ballaststoffreich"],
  },
  {
    plant: "Spitzwegerich",
    "Botanische Familie": "Wegerichgewächse",
    discomfort: ["Erkältungs-Beschwerden", "Gicht- / Rheumabeschwerden"],
    effect: ["Auswurffördernd", "Entwässernd"],
  },
  {
    plant: "Tausendgüldenkraut",
    "Botanische Familie": "Enziangewächse",
    discomfort: ["Gicht- / Rheumabeschwerden", "Bindegewebsschwäche"],
    effect: ["Gallenflussfördernd"],
  },
  {
    plant: "Teebaumöl",
    "Botanische Familie": "Myrtengewächse",
    discomfort: ["Mund- / Zahn-Hygiene", "Erkältungs-Beschwerden", "Haut-Probleme", "Gelenk-Beschwerden"],
    effect: ["Immunsystemkräftigend"],
  },
  {
    plant: "Thymian",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Asthma-Beschwerden", "Erkältungs-Beschwerden", "Verdauungs-Probleme"],
  },
  {
    plant: "Wacholderbeere",
    "Botanische Familie": "Zypressengewächse",
    discomfort: ["Blasen- / Harnwegsbeschwerden"],
  },
  {
    plant: "Weidenröschen",
    "Botanische Familie": "Nachtkerzengewächse",
    discomfort: ["Blasen- / Harnwegsbeschwerden", "Nieren-Beschwerden", "Stoffwechsel-Beschwerden"],
    effect: ["Entwässernd", "Entsäuernd", "Entgiftend"],
  },
  {
    plant: "Weißdorn",
    "Botanische Familie": "Rosengewächse",
    discomfort: ["Appetitanregend"],
    effect: ["Herzkräftigend", "Blutdruckregulierend"],
  },
  {
    plant: "Wermut",
    "Botanische Familie": "Korbblütler",
    discomfort: ["Magen-Beschwerden", "Leber- / Galle-Beschwerden", "Verdauungs-Beschwerden", "Erkältungs-Beschwerden", "Gelenk-Beschwerden"],
  },
  {
    plant: "Ysop",
    "Botanische Familie": "Lippenblütler",
    discomfort: ["Magen-Beschwerden", "Stoffwechsel-Beschwerden", "Blutniederdruck"],
    effect: ["Blutreinigung", "Immunsystemkräftigend"],
  },
  {
    plant: "Zimt",
    "Botanische Familie": "Lorbeergewächse",
    discomfort: ["Verdauungs-Beschwerden", "Blutniederdruck"],
    effect: ["Nervensystemstärkend", "Immunsystemkräftigend", "Appetitanregend"],
  },
  {
    plant: "Zinnkraut",
    "Botanische Familie": "Schachtelhalmgewächse",
    discomfort: ["Blutreinigung", "Blasen- / Harnwegsbeschwerden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Beschwerden", "Erkältungs-Beschwerden"],
  },
  {
    plant: "Zwiebel",
    "Botanische Familie": "Liliengewächse",
    discomfort: ["Blasen- / Harnwegsbeschwerden", "Erkältungs-Beschwerden", "Magen-Beschwerden", "Gicht- / Rheumabeschwerden", "Stoffwechsel-Probleme"],
    effect: ["Blutreinigend", "Immunsystemkräftigend"],
  },
];

export const Data_Nummernschild = [
  ["0", "Diplomatisches Corps"],
  [0 - 1, "Dienstkraftwagen des Bundespräsidenten"],
  [0 - 2, "Dienstkraftwagen des Bundeskanzlers"],
  [1 - 1, "Dienstkraftwagen des Bundestagspräsidenten"],
  ["A", "Augsburg"],
  ["AA", "Ostalbkreis (Aalen)"],
  ["AB", "Aschaffenburg"],
  ["ABG", "Altenburg"],
  ["AC", "Aachen"],
  ["AD", "US-Streitkräfte in Deutschland"],
  ["AE", "Auerbach"],
  ["AF", "US-Streitkräfte in Deutschland"],
  ["AH", "Ahaus"],
  ["AIB", "Bad Aibling"],
  ["AIC", "Aichach-Friedberg (Aichach)"],
  ["AK", "Altenkirchen [Westerwald]"],
  ["AL", "Altena [Westfalen]"],
  ["ALF", "Alfeld [Leine]"],
  ["ALS", "Alsfeld [Oberhessen]"],
  ["ALZ", "Alzenau [Unterfranken]"],
  ["AM", "Amberg"],
  ["AN", "Ansbach"],
  ["ANA", "Annaberg (Annaberg-Buchholz)"],
  ["ANG", "Angermünde"],
  ["ANK", "Anklam"],
  ["AÖ", "Altötting"],
  ["AP", "Weimarer Land (Apolda)"],
  ["APD", "Apolda"],
  ["AR", "Arnsberg [Westfalen]"],
  ["ARN", "Arnstadt"],
  ["ART", "Artern"],
  ["AS", "Amberg-Sulzbach (Amberg)"],
  ["ASD", "Aschendorf-Hümmling (Papenburg-Aschendorf)"],
  ["ASL", "Aschersleben-Stassfurter Landkreis (Aschersleben)"],
  ["ASZ", "Westerzgebirgskreis (Aue/Schwarzenberg)"],
  ["AT", "Altentreptow"],
  ["AU", "Aue"],
  ["AUR", "Aurich"],
  ["AW", "Ahrweiler (Bad Neuenahr-Ahrweiler)"],
  ["AZ", "Alzey-Worms (Alzey)"],
  ["AZE", "Anhalt-Zerbst (Coswig)"],
  ["B", "Berlin"],
  ["BA", "Bamberg"],
  ["BAD", "Baden-Baden"],
  ["BAR", "Barnim (Eberswalde)"],
  ["BB", "Böblingen"],
  ["BBG", "Bernburg"],
  ["BBL", "Brandenburg"],
  ["BC", "Biberach [Riß]"],
  ["BCH", "Buchen [Odenwald]"],
  ["BD", "Bundestag, Bundesrat, Bundesregierung"],
  ["BE", "Beckum [Westfalen]"],
  ["BED", "Brand-Erbisdorf"],
  ["BEI", "Beilngries"],
  ["BEL", "Belzig"],
  ["BER", "Bernau [bei Berlin]"],
  ["BF", "Steinfurt (Burgsteinfurt)"],
  ["BG", "Bundesgrenzschutz"],
  ["BGD", "Berchtesgaden"],
  ["BGL", "Berchtesgadener Land (Bad Reichenhall)"],
  ["BH", "Bühl [Baden]"],
  ["BI", "Bielefeld"],
  ["BID", "Biedenkopf"],
  ["BIN", "Bingen [Rhein]"],
  ["BIR", "Birkenfeld [Nahe]"],
  ["BIT", "Bitburg-Prüm (Bitburg)"],
  ["BIW", "Bischofswerda"],
  ["BK", "Backnang"],
  ["BKS", "Bernkastel (Bernkastel-Kues)"],
  ["BL", "Zollernalbkreis (Balingen)"],
  ["BLB", "Wittgenstein (Bad Berleburg)"],
  ["BLK", "Burgenlandkreis (Naumburg)"],
  ["BM", "Erftkreis (Bergheim)"],
  ["BN", "Bonn"],
  ["BNA", "Borna"],
  ["BO", "Bochum"],
  ["BOG", "Bogen"],
  ["BOH", "Bocholt"],
  ["BOR", "Borken"],
  ["BÖ", "Bördekreis (Oschersleben)"],
  ["BOT", "Bottrop"],
  ["BP", "Deutsche Bundespost (<1997)"],
  ["BR", "Bruchsal"],
  ["BRA", "Wesermarsch (Brake [Unterweser])"],
  ["BRB", "Brandenburg [Landkreis]"],
  ["BRB", "Brandenburg [Stadt]"],
  ["BRG", "Burg"],
  ["BRI", "Brilon"],
  ["BRK", "Bad Brückenau"],
  ["BRL", "Blankenburg (Braunlage [Harz])"],
  ["BRV", "Bremervörde"],
  ["BS", "Braunschweig"],
  ["BSB", "Bersenbrück"],
  ["BSK", "Beeskow"],
  ["BT", "Bayreuth"],
  ["BTF", "Bitterfeld"],
  ["BU", "Burgdorf [bei Lehrte]"],
  ["BÜD", "Büdingen [Oberhessen]"],
  ["BUL", "Burglengenfeld"],
  ["BÜR", "Büren [Westfalen]"],
  ["BÜS", "Büsingen am Hochrhein"],
  ["BÜZ", "Bützow"],
  ["BW", "Bundes-Wasser- und Schiffahrtsverwaltung"],
  ["BWL", "Baden-Württemberg"],
  ["BYL", "Bayern"],
  ["BZ", "Bautzen"],
  ["BZA", "Bergzabern"],
  ["C", "Chemnitz [Landkreis]"],
  ["C", "Chemnitz [Stadt]"],
  ["CA", "Calau"],
  ["CAS", "Castrop-Rauxel"],
  ["CB", "Cottbus [Landkreis]"],
  ["CB", "Cottbus [Stadt]"],
  ["CE", "Celle"],
  ["CHA", "Cham [Oberpfalz]"],
  ["CLP", "Cloppenburg"],
  ["CLZ", "Clausthal-Zellerfeld"],
  ["CO", "Coburg"],
  ["COC", "Cochem-Zell (Cochem)"],
  ["COE", "Coesfeld [Westfalen]"],
  ["CR", "Crailsheim"],
  ["CUX", "Cuxhaven"],
  ["CW", "Calw"],
  ["D", "Düsseldorf"],
  ["DA", "Darmstadt"],
  ["DAH", "Dachau"],
  ["DAN", "Lüchow-Dannenberg (Lüchow)"],
  ["DAU", "Daun [Eifel]"],
  ["DB", "Deutsche Bundesbahn"],
  ["DBR", "Bad Doberan"],
  ["DD", "Dresden"],
  ["DE", "Dessau"],
  ["DEG", "Deggendorf"],
  ["DEL", "Delmenhorst [Stadt]"],
  ["DGF", "Dingolfing-Landau (Dingolfing)"],
  ["DH", "Diepholz"],
  ["DI", "Dieburg"],
  ["DIL", "Dillkreis (Dillenburg)"],
  ["DIN", "Dinslaken"],
  ["DIZ", "Unterlahnkreis (Diez)"],
  ["DKB", "Dinkelsbühl"],
  ["DL", "Döbeln"],
  ["DLG", "Dillingen [Donau]"],
  ["DM", "Demmin"],
  ["DN", "Düren"],
  ["DO", "Dortmund"],
  ["DON", "Donau-Ries (Donauwörth)"],
  ["DS", "Donaueschingen"],
  ["DT", "Lippe (Detmold)"],
  ["DU", "Duisburg"],
  ["DUD", "Duderstadt"],
  ["DÜW", "Bad Dürkheim [Weinstraße]"],
  ["DW", "Weisseritzkreis (Dippoldiswalde)"],
  ["DZ", "Delitzsch"],
  ["E", "Essen"],
  ["EA", "Eisenach [Stadt]"],
  ["EB", "Eilenburg"],
  ["EBE", "Ebersberg"],
  ["EBN", "Ebern"],
  ["EBS", "Ebermannstadt"],
  ["ECK", "Eckernförde"],
  ["ED", "Erding"],
  ["EE", "Elbe-Elster (Herzberg)"],
  ["EF", "Erfurt [Landkreis]"],
  ["EF", "Erfurt [Stadt]"],
  ["EG", "Eggenfelden"],
  ["EH", "Eisenhüttenstadt"],
  ["EHI", "Ehingen [Donau]"],
  ["EI", "Eichstätt"],
  ["EIC", "Eichsfeld (Heiligenstadt)"],
  ["EIH", "Eichstätt"],
  ["EIL", "Eisleben"],
  ["EIN", "Einbeck"],
  ["EIS", "Eisenberg"],
  ["EL", "Emsland (Meppen)"],
  ["EM", "Emmendingen"],
  ["EMD", "Emden"],
  ["EMS", "Rhein-Lahn-Kreis (Bad Ems)"],
  ["EN", "Ennepe-Ruhr-Kreis (Schwelm)"],
  ["ER", "Erlangen"],
  ["ERB", "Odenwaldkreis (Erbach [Odenwald])"],
  ["ERH", "Erlangen-Höchstadt (Erlangen)"],
  ["ERK", "Erkelenz"],
  ["ES", "Esslingen [Neckar]"],
  ["ESA", "Eisenach"],
  ["ESB", "Eschenbach [Oberpfalz]"],
  ["ESW", "Werra-Meißner-Kreis (Eschwege)"],
  ["EU", "Euskirchen"],
  ["EUT", "Eutin"],
  ["EW", "Eberswalde"],
  ["F", "Frankfurt am Main [Stadt]"],
  ["FAL", "Soltau-Fallingbostel (Fallingbostel)"],
  ["FB", "Wetteraukreis (Friedberg [Hessen])"],
  ["FD", "Fulda"],
  ["FDB", "Friedberg [Bayern]"],
  ["FDS", "Freudenstadt"],
  ["FEU", "Feuchtwangen"],
  ["FF", "Frankfurt [Oder]"],
  ["FFB", "Fürstenfeldbruck"],
  ["FG", "Freiberg [Sachsen]"],
  ["FH", "Main-Taunus-Kreis (Frankfurt am Main-Höchst)"],
  ["FI", "Finsterwalde"],
  ["FKB", "Frankenberg [Eder]"],
  ["FL", "Flensburg"],
  ["FLÖ", "Flöha"],
  ["FN", "Bodenseekreis (Friedrichshafen)"],
  ["FO", "Forchheim"],
  ["FOR", "Forst"],
  ["FR", "Breisgau-Hochschwarzwald (Freiburg [Breisgau])"],
  ["FRG", "Freyung-Grafenau (Freyung)"],
  ["FRI", "Friesland (Jever)"],
  ["FRW", "Bad Freienwalde"],
  ["FS", "Freising"],
  ["FT", "Frankenthal [Pfalz]"],
  ["FTL", "Freital"],
  ["FÜ", "Fürth [Bayern]"],
  ["FÜS", "Füssen"],
  ["FW", "Fürstenwalde"],
  ["FZ", "Fritzlar-Homberg (Fritzlar)"],
  ["G", "Gera [Landkreis]"],
  ["G", "Gera [Stadt]"],
  ["GA", "Gardelegen"],
  ["GAN", "Gandersheim (Bad Gandersheim)"],
  ["GAP", "Garmisch-Partenkirchen"],
  ["GC", "Chemnitzer Land (Glauchau)"],
  ["GD", "Schwäbisch Gmünd (<1972->AA)"],
  ["GDB", "Gadebusch"],
  ["GE", "Gelsenkirchen"],
  ["GEL", "Geldern"],
  ["GEM", "Gemünden [Main]"],
  ["GEO", "Gerolzhofen"],
  ["GER", "Germersheim"],
  ["GF", "Gifhorn"],
  ["GG", "Groß-Gerau"],
  ["GHA", "Geithain"],
  ["GHC", "Gräfenhainichen"],
  ["GI", "Gießen (<1976->L,>1979)"],
  ["GK", "Geilenkirchen-Heinsberg (Erkelenz)"],
  ["GL", "Rheinisch-Bergischer Kreis (Bergisch Gladbach)"],
  ["GLA", "Gladbeck [Westfalen]"],
  ["GM", "Oberbergischer Kreis (Gummersbach)"],
  ["GMN", "Grimmen"],
  ["GN", "Gelnhausen"],
  ["GNT", "Genthin"],
  ["GOA", "Sankt Goar"],
  ["GÖ", "Göttingen"],
  ["GOH", "Sankt Goarshausen"],
  ["GP", "Göppingen"],
  ["GR", "Görlitz [Landkreis]"],
  ["GR", "Görlitz [Stadt]"],
  ["GRA", "Grafenau"],
  ["GRH", "Großenhain"],
  ["GRI", "Griesbach Rottal"],
  ["GRM", "Grimma"],
  ["GRS", "Gransee"],
  ["GRZ", "Greiz"],
  ["GS", "Goslar"],
  ["GT", "Gütersloh"],
  ["GTH", "Gotha"],
  ["GÜ", "Güstrow"],
  ["GUB", "Guben"],
  ["GUN", "Gunzenhausen"],
  ["GV", "Grevenbroich"],
  ["GVM", "Grevesmühlen"],
  ["GW", "Greifswald [Landkreis]"],
  ["GZ", "Günzburg"],
  ["H", "Hannover"],
  ["HA", "Hagen [Westfalen]"],
  ["HAB", "Hammelburg"],
  ["HAL", "Halle [Saale]"],
  ["HAM", "Hamm [Westfalen]"],
  ["HAS", "Haßberge (Haßfurt)"],
  ["HB", "Hansestadt Bremen und Bremerhaven"],
  ["HBN", "Hildburghausen"],
  ["HBS", "Halberstadt"],
  ["HC", "Hainichen"],
  ["HCH", "Hechingen"],
  ["HD", "Rhein-Neckar-Kreis und Heidelberg (Heidelberg)"],
  ["HDH", "Heidenheim [Brenz]"],
  ["HDL", "Haldensleben"],
  ["HE", "Helmstedt"],
  ["HEB", "Hersbruck"],
  ["HEF", "Hersfeld-Rotenburg (Bad Hersfeld)"],
  ["HEI", "Dithmarschen (Heide [Holstein])"],
  ["HEL", "Hessen"],
  ["HER", "Herne"],
  ["HET", "Hettstedt"],
  ["HF", "Herford"],
  ["HG", "Hochtaunuskreis (Bad Homburg vor der Höhe)"],
  ["HGN", "Hagenow"],
  ["HGW", "Hansestadt Greifswald"],
  ["HH", "Hansestadt Hamburg"],
  ["HHM", "Hohenmölsen"],
  ["HI", "Hildesheim"],
  ["HIG", "Heiligenstadt"],
  ["HIP", "Hilpoltstein [Mittelfranken]"],
  ["HK", "US-Streitkräfte in Deutschland"],
  ["HL", "Hansestadt Lübeck"],
  ["HM", "Hameln-Pyrmont (Hameln)"],
  ["HMÜ", "Hannoversch Münden"],
  ["HN", "Heilbronn [Neckar]"],
  ["HO", "Hof [Saale]"],
  ["HOG", "Hofgeismar"],
  ["HOH", "Hofheim [Unterfranken]"],
  ["HOL", "Holzminden"],
  ["HOM", "Saar-Pfalz-Kreis (Homburg [Saar])"],
  ["HOR", "Horb [Neckar]"],
  ["HÖS", "Höchstadt [Aisch]"],
  ["HOT", "Hohenstein-Ernstthal"],
  ["HP", "Bergstraße (Heppenheim [Bergstraße])"],
  ["HR", "Schwalm-Eder-Kreis (Homberg [Efze])"],
  ["HRO", "Hansestadt Rostock"],
  ["HS", "Heinsberg"],
  ["HSK", "Hochsauerlandkreis (Meschede)"],
  ["HST", "Hansestadt Stralsund"],
  ["HU", "Main-Kinzig-Kreis (Hanau)"],
  ["HÜN", "Hünfeld"],
  ["HUS", "Husum"],
  ["HV", "Havelberg"],
  ["HVL", "Havelland (Rathenow)"],
  ["HW", "Halle [Westfalen]"],
  ["HWI", "Hansestadt Wismar"],
  ["HX", "Höxter"],
  ["HY", "Hoyerswerda"],
  ["HZ", "Herzberg"],
  ["IGB", "St. Ingbert"],
  ["IK", "Ilmkreis (Arnstadt)"],
  ["IL", "Ilmenau"],
  ["ILL", "Illertissen"],
  ["IN", "Ingolstadt"],
  ["IS", "Iserlohn"],
  ["IZ", "Steinburg (Itzehoe)"],
  ["J", "Jena [Landkreis]"],
  ["J", "Jena"],
  ["JB", "Jüterbog"],
  ["JE", "Jessen"],
  ["JEV", "Friesland (Jever)"],
  ["JL", "Jerichower Land (Burg b. Magdeburg)"],
  ["JÜL", "Jülich"],
  ["K", "Köln"],
  ["KA", "Karlsruhe"],
  ["KAR", "Main-Spessart-Kreis (Karlstadt)"],
  ["KB", "Waldeck-Frankenberg (Korbach)"],
  ["KC", "Kronach"],
  ["KE", "Kempten [Allgäu]"],
  ["KEH", "Kelheim"],
  ["KEL", "Kehl"],
  ["KEM", "Kemnath"],
  ["KF", "Kaufbeuren"],
  ["KG", "Bad Kissingen"],
  ["KH", "Bad Kreuznach"],
  ["KI", "Kiel [Stadt]"],
  ["KIB", "Donnersberg-Kreis (Kirchheimbolanden)"],
  ["KK", "Kempen-Krefeld (Kempen [Niederrhein])"],
  ["KL", "Kaiserslautern"],
  ["KLE", "Kleve"],
  ["KLZ", "Klötze"],
  ["KM", "Kamenz"],
  ["KN", "Konstanz"],
  ["KO", "Koblenz [Landkreis]"],
  ["KO", "Koblenz [Stadt]"],
  ["KÖN", "Königshofen [Grabfeld]"],
  ["KÖT", "Köthen"],
  ["KÖZ", "Kötzting"],
  ["KR", "Krefeld"],
  ["KRU", "Krumbach [Schwaben]"],
  ["KS", "Kassel"],
  ["KT", "Kitzingen"],
  ["KU", "Kulmbach"],
  ["KÜN", "Hohenlohe-Kreis (Künzelsau)"],
  ["KUS", "Kusel"],
  ["KW", "Königs Wusterhausen"],
  ["KY", "Kyritz"],
  ["KYF", "Kyffhäuserkreis (Sondershausen)"],
  ["L", "Lahn-Dill-Kreis (Wetzlar)"],
  ["L", "Leipzig"],
  ["LA", "Landshut [Bayern]"],
  ["LAN", "Landau [Isar]"],
  ["LAT", "Vogelsberg-Kreis (Lauterbach [Hessen])"],
  ["LAU", "Nürnberger Land (Lauf [Pegnitz])"],
  ["LB", "Ludwigsburg"],
  ["LBS", "Lobenstein"],
  ["LBZ", "Lübz"],
  ["LC", "Luckau"],
  ["LD", "Landau [Pfalz]"],
  ["LDK", "Lahn-Dill-Kreis (Wetzlar)"],
  ["LDS", "Dahme-Spreewald (Lübben)"],
  ["LE", "Lemgo"],
  ["LEO", "Leonberg [Württemberg]"],
  ["LER", "Leer [Ostfriesland]"],
  ["LEV", "Leverkusen"],
  ["LF", "Laufen [Salzach]"],
  ["LG", "Lüneburg"],
  ["LH", "Lüdinghausen"],
  ["LI", "Lindau [Bodensee]"],
  ["LIB", "Bad Liebenwerda"],
  ["LIF", "Lichtenfels"],
  ["LIN", "Lingen [Ems]"],
  ["LIP", "Lippe (Detmold)"],
  ["LK", "Lübbecke [Westfalen]"],
  ["LL", "Landsberg [Lech]"],
  ["LM", "Limburg-Weilburg (Limburg [Lahn])"],
  ["LN", "Lübben"],
  ["LÖ", "Lörrach"],
  ["LÖB", "Löbau"],
  ["LOH", "Lohr [Main]"],
  ["LOS", "Oder-Spree (Beeskow)"],
  ["LP", "Lippstadt"],
  ["LR", "Lahr [Schwarzwald]"],
  ["LS", "Märkischer Kreis (Lüdenscheid) (>1975,<1979->MK)"],
  ["LSA", "Sachsen-Anhalt"],
  ["LSN", "Sachsen"],
  ["LSZ", "Bad Langensalza"],
  ["LU", "Ludwigshafen"],
  ["LÜD", "Lüdenscheid"],
  ["LUK", "Luckenwalde"],
  ["LÜN", "Lünen"],
  ["LWL", "Ludwigslust"],
  ["M", "München"],
  ["MA", "Mannheim"],
  ["MAB", "Marienberg"],
  ["MAI", "Mainburg"],
  ["MAK", "Marktredwitz"],
  ["MAL", "Mallersdorf"],
  ["MAR", "Marktheidenfeld"],
  ["MB", "Miesbach"],
  ["MC", "Malchin"],
  ["MD", "Magdeburg"],
  ["ME", "Mettmann"],
  ["MED", "Süderdithmarschen (Meldorf)"],
  ["MEG", "Melsungen"],
  ["MEI", "Meißen"],
  ["MEK", "Mittlerer Erzgebirgskreis (Marienberg)"],
  ["MEL", "Melle"],
  ["MEP", "Meppen"],
  ["MER", "Merseburg"],
  ["MES", "Hochsauerlandkreis (Meschede)"],
  ["MET", "Mellrichstadt"],
  ["MG", "Mönchengladbach"],
  ["MGH", "Bad Mergentheim"],
  ["MGN", "Meiningen"],
  ["MH", "Mülheim [Ruhr]"],
  ["MHL", "Mühlhausen"],
  ["MI", "Minden-Lübbecke (Minden [Westfalen])"],
  ["MIL", "Miltenberg"],
  ["MK", "Märkischer Kreis (Lüdenscheid)"],
  ["ML", "Mansfelder Land (Lutherstadt Eisleben)"],
  ["MM", "Memmingen"],
  ["MN", "Unterallgäu (Mindelheim)"],
  ["MO", "Moers"],
  ["MOD", "Ostallgäu (Marktoberdorf)"],
  ["MOL", "Märkisch-Oderland (Seelow)"],
  ["MON", "Monschau"],
  ["MOS", "Neckar-Odenwald-Kreis (Mosbach)"],
  ["MQ", "Merseburg-Querfurt (Merseburg)"],
  ["MR", "Marburg-Biedenkopf (Marburg [Lahn])"],
  ["MS", "Münster [Westfalen]"],
  ["MSP", "Main-Spessart (Karlstadt)"],
  ["MST", "Mecklenburg-Strelitz (Neustrelitz)"],
  ["MT", "Westerwald (Montabaur)"],
  ["MTK", "Main-Taunus-Kreis (Hofheim am Taunus)"],
  ["MTL", "Muldentalkreis (Grimma)"],
  ["MÜ", "Mühldorf am Inn"],
  ["MÜB", "Münchberg [Oberfranken]"],
  ["MÜL", "Müllheim [Baden]"],
  ["MÜN", "Münsingen [Württemberg]"],
  ["MÜR", "Müritz (Waren)"],
  ["MVL", "Mecklenburg-Vorpommern"],
  ["MW", "Mittweida"],
  ["MY", "Mayen"],
  ["MYK", "Mayen-Koblenz (Koblenz)"],
  ["MZ", "Mainz"],
  ["MZG", "Merzig-Wadern (Merzig [Saar])"],
  ["N", "Nürnberg [Stadt]"],
  ["NAB", "Nabburg"],
  ["NAI", "Naila"],
  ["NAU", "Nauen"],
  ["NB", "Neubrandenburg [Landkreis]"],
  ["NB", "Neubrandenburg [Stadt]"],
  ["ND", "Neuburg-Schrobenhausen (Neuburg [Donau])"],
  ["NDH", "Nordhausen"],
  ["NE", "Neuss"],
  ["NEA", "Neustadt an der Aisch-Bad Windsheim"],
  ["NEB", "Nebra [Unstrut]"],
  ["NEC", "Neustadt [bei Coburg]"],
  ["NEN", "Neunburg vorm Wald"],
  ["NES", "Rhön-Grabfeld (Bad Neustadt [Saale])"],
  ["NEU", "Hochschwarzwald (Titisee-Neustadt)"],
  ["NEW", "Neustadt [an der Waldnaab]"],
  ["NF", "Nordfriesland (Husum)"],
  ["NH", "Neuhaus [Rennweg]"],
  ["NI", "Nienburg [Weser]"],
  ["NIB", "Süd-Tondern (Niebüll)"],
  ["NK", "Neunkirchen [Saar]"],
  ["NL", "Niedersachsen"],
  ["NM", "Neumarkt [Oberpfalz]"],
  ["NMB", "Naumburg [Saale]"],
  ["NMS", "Neumünster"],
  ["NÖ", "Nördlingen"],
  ["NOH", "Grafschaft Bentheim (Nordhorn)"],
  ["NOL", "Niederschlesischer Oberlausitzkreis (Görlitz)"],
  ["NOM", "Northeim"],
  ["NOR", "Norden"],
  ["NRW", "Nordrhein-Westfalen"],
  ["NP", "Neuruppin"],
  ["NR", "Neuwied [Rhein]"],
  ["NRÜ", "Neustadt [am Rübenberge]"],
  ["NT", "Nürtingen"],
  ["NU", "Neu-Ulm"],
  ["NVP", "Nordvorpommern (Grimmen)"],
  ["NW", "Neustadt [Weinstraße] [Stadt]"],
  ["NWM", "Nordwestmecklenburg (Grevesmühlen)"],
  ["NY", "Niesky"],
  ["NZ", "Neustrelitz"],
  ["OA", "Oberallgäu (Sonthofen)"],
  ["OAL", "Ostallgäu (Marktoberdorf) (>1979)"],
  ["OB", "Oberhausen [Rheinland]"],
  ["OBB", "Obernburg [Main]"],
  ["OBG", "Osterburg"],
  ["OC", "Oschersleben"],
  ["OCH", "Ochsenfurt"],
  ["OD", "Stormarn (Bad Oldesloe)"],
  ["OE", "Olpe"],
  ["OF", "Offenbach [Main]"],
  ["OG", "Ortenaukreis (Offenburg)"],
  ["OH", "Ostholstein (Eutin)"],
  ["OHA", "Osterode [am Harz]"],
  ["ÖHR", "Öhringen [Württemberg]"],
  ["OHV", "Oberhavel (Oranienburg)"],
  ["OHZ", "Osterholz (Osterholz-Scharmbeck)"],
  ["OK", "Ohrekreis (Haldensleben)"],
  ["OL", "Oldenburg [Oldenburg]"],
  ["OLD", "Oldenburg [Holstein]"],
  ["OP", "Rhein-Wupper-Kreis (Opladen)"],
  ["OPR", "Ostprignitz-Ruppin (Neuruppin)"],
  ["OR", "Oranienburg"],
  ["OS", "Osnabrück"],
  ["OSL", "Oberspreewald-Lausitz (Senftenberg)"],
  ["OTT", "Land Hadeln (Otterndorf)"],
  ["OTW", "Ottweiler [Saar]"],
  ["OVI", "Oberviechtach"],
  ["OVL", "Obervogtland (Oelsnitz und Klingenthal)"],
  ["OVP", "Ostvorpommern (Anklam)"],
  ["OZ", "Oschatz (>1991,<1995->TO)"],
  ["P", "Potsdam [Landkreis]"],
  ["P", "Potsdam [Stadt]"],
  ["PA", "Passau"],
  ["PAF", "Pfaffenhofen [an der Ilm]"],
  ["PAN", "Rottal-Inn (Pfarrkirchen [Inn])"],
  ["PAR", "Parsberg"],
  ["PB", "Paderborn"],
  ["PCH", "Parchim"],
  ["PE", "Peine"],
  ["PEG", "Pegnitz"],
  ["PER", "Perleberg"],
  ["PF", "Enzkreis und Pforzheim (Pforzheim)"],
  ["PI", "Pinneberg"],
  ["PIR", "Sächsische Schweiz (Pirna)"],
  ["PK", "Pritzwalk"],
  ["PL", "Plauen [Landkreis]"],
  ["PL", "Plauen [Stadt]"],
  ["PLÖ", "Plön (Holstein)"],
  ["PM", "Potsdam-Mittelmark (Belzig)"],
  ["PN", "Pößneck"],
  ["PR", "Prignitz (Perleberg)"],
  ["PRÜ", "Prüm [Eifel]"],
  ["PS", "Pirmasens"],
  ["PW", "Pasewalk"],
  ["PZ", "Prenzlau"],
  ["QFT", "Querfurt"],
  ["QLB", "Quedlinburg"],
  ["R", "Regensburg"],
  ["RA", "Rastatt"],
  ["RC", "Reichenbach [Vogtland]"],
  ["RD", "Rendsburg-Eckernförde (Rendsburg)"],
  ["RDG", "Ribnitz-Damgarten"],
  ["RE", "Recklinghausen"],
  ["REG", "Regen"],
  ["REH", "Rehau"],
  ["REI", "Berchtesgadener Land (Bad Reichenhall)"],
  ["RG", "Riesa-Großenhain (Großenhain)"],
  ["RH", "Roth"],
  ["RI", "Grafschaft Schaumburg (Rinteln)"],
  ["RID", "Riedenburg [Bayern]"],
  ["RIE", "Riesa"],
  ["RL", "Rochlitz"],
  ["RM", "Röbel [Müritz]"],
  ["RN", "Rathenow"],
  ["RO", "Rosenheim"],
  ["ROD", "Roding"],
  ["ROF", "Rotenburg [Fulda]"],
  ["ROH", "Rotenburg [Wümme, Hannover]"],
  ["ROK", "Rockenhausen"],
  ["ROL", "Rottenburg [Laaber]"],
  ["ROS", "Rostock [Landkreis]"],
  ["ROT", "Rothenburg ob der Tauber"],
  ["ROW", "Rotenburg [Wümme]"],
  ["RPL", "Rheinland-Pfalz"],
  ["RS", "Remscheid"],
  ["RSL", "Rosslau [Elbe]"],
  ["RT", "Reutlingen"],
  ["RU", "Rudolstadt"],
  ["RÜD", "Rheingau-Taunus-Kreis (Rüdesheim [Rhein])"],
  ["RÜG", "Rügen (Bergen)"],
  ["RV", "Ravensburg"],
  ["RW", "Rottweil"],
  ["RWL", "Nordrhein-Westfalen"],
  ["RY", "Rheydt"],
  ["RZ", "Herzogtum Lauenburg (Ratzeburg)"],
  ["S", "Stuttgart"],
  ["SAB", "Saarburg [Bezirk Trier]"],
  ["SAD", "Schwandorf"],
  ["SÄK", "Säckingen"],
  ["SAL", "Saarland"],
  ["SAN", "Stadtsteinach"],
  ["SAW", "Salzwedel"],
  ["SB", "Saarbrücken"],
  ["SBG", "Strasburg"],
  ["SBK", "Schönebeck [Elbe]"],
  ["SC", "Schwabach"],
  ["SCZ", "Schleiz"],
  ["SD", "Stade"],
  ["SDH", "Sondershausen"],
  ["SDL", "Stendal"],
  ["SDT", "Schwedt [Oder]"],
  ["SE", "Segeberg (Bad Segeberg)"],
  ["SEB", "Sebnitz"],
  ["SEE", "Seelow"],
  ["SEF", "Scheinfeld"],
  ["SEL", "Selb"],
  ["SF", "Oberallgäu (Sonthofen)"],
  ["SFA", "Soltau-Fallingbostel (Fallingbostel)"],
  ["SFB", "Senftenberg"],
  ["SFT", "Staßfurt"],
  ["SG", "Solingen"],
  ["SGH", "Sangerhausen"],
  ["SH", "Schleswig-Holstein"],
  ["SHA", "Schwäbisch Hall"],
  ["SHG", "Schaumburg (Stadthagen)"],
  ["SHK", "Saale-Holzland-Kreis (Eisenberg)"],
  ["SHL", "Suhl [Landkreis]"],
  ["SHL", "Suhl [Stadt]"],
  ["SI", "Siegen"],
  ["SIG", "Sigmaringen"],
  ["SIM", "Rhein-Hunsrück-Kreis (Simmern)"],
  ["SK", "Saalkreis (Halle)"],
  ["SL", "Schleswig-Flensburg (Schleswig)"],
  ["SLE", "Schleiden [Eifel]"],
  ["SLF", "Saalfeld-Rudolstadt (Saalfeld)"],
  ["SLG", "Saulgau"],
  ["SLN", "Schmölln"],
  ["SLS", "Saarlouis"],
  ["SLÜ", "Schlüchtern"],
  ["SLZ", "Bad Salzungen"],
  ["SM", "Schmalkalden-Meiningen"],
  ["SMÜ", "Schwabmünchen"],
  ["SN", "Schwerin [Landkreis]"],
  ["SN", "Schwerin [Stadt]"],
  ["SNH", "Sinsheim [Elsenz]"],
  ["SO", "Soest"],
  ["SOB", "Schrobenhausen"],
  ["SOG", "Schongau"],
  ["SOK", "Saale-Orla-Kreis (Schleiz)"],
  ["SOL", "Soltau"],
  ["SÖM", "Sömmerda"],
  ["SON", "Sonneberg"],
  ["SP", "Speyer"],
  ["SPB", "Spremberg"],
  ["SPN", "Spree-Neisse (Forst)"],
  ["SPR", "Springe [Deister]"],
  ["SR", "Straubing"],
  ["SRB", "Strausberg"],
  ["SRO", "Stadtroda"],
  ["ST", "Stade"],
  ["ST", "Steinfurt"],
  ["STA", "Starnberg"],
  ["STB", "Sternberg"],
  ["STD", "Stade"],
  ["STE", "Staffelstein"],
  ["STH", "Schaumburg-Lippe (Stadthagen)"],
  ["STL", "Stollberg"],
  ["STO", "Stockach [Baden]"],
  ["SU", "Rhein-Sieg-Kreis (Siegburg)"],
  ["SUL", "Sulzbach-Rosenberg"],
  ["SÜW", "Südliche Weinstraße (Landau [Pfalz])"],
  ["SW", "Schweinfurt"],
  ["SWA", "Rheingau-Taunus-Kreis (Bad Schwalbach)"],
  ["SY", "Grafschaft Hoya (Syke)"],
  ["SZ", "Salzgitter"],
  ["SZB", "Schwarzenberg"],
  ["TBB", "Main-Tauber-Kreis (Tauberbischofsheim)"],
  ["TE", "Tecklenburg (<1974->ST)"],
  ["TET", "Teterow"],
  ["TF", "Teltow-Flaeming (Luckenwalde)"],
  ["TG", "Torgau (>1991,<1995->TO)"],
  ["THL", "Thüringen"],
  ["THW", "Technisches Hilfswerk"],
  ["TIR", "Tirschenreuth"],
  ["TO", "Torgau-Oschatz (Torgau)"],
  ["TÖL", "Bad Tölz-Wolfratshausen (Bad Tölz)"],
  ["TÖN", "Eiderstedt (Tönning)"],
  ["TP", "Templin [Uckermark]"],
  ["TR", "Trier-Saarburg und Trier"],
  ["TS", "Traunstein [Oberbayern]"],
  ["TT", "Tettnang [Württemberg]"],
  ["TÜ", "Tübingen"],
  ["TUT", "Tuttlingen"],
  ["ÜB", "Überlingen [Bodensee]"],
  ["UE", "Uelzen"],
  ["UEM", "Ueckermünde"],
  ["UER", "Uecker-Randow (Pasewalk)"],
  ["UFF", "Uffenheim"],
  ["UH", "Unstrut-Hainich (Mühlhausen)"],
  ["UL", "Alb-Donau-Kreis und Ulm"],
  ["UM", "Uckermark (Prenzlau)"],
  ["UN", "Unna [Westfalen]"],
  ["USI", "Usingen [Taunus]"],
  ["V", "Vogtlandkreis"],
  ["VAI", "Vaihingen [Enz]"],
  ["VB", "Vogelsbergkreis (Lauterbach [Hessen])"],
  ["VEC", "Vechta"],
  ["VER", "Verden [Aller]"],
  ["VIB", "Vilsbiburg"],
  ["VIE", "Viersen"],
  ["VIT", "Viechtach"],
  ["VK", "Völklingen (Stadt) (>1968)"],
  ["VL", "Villingen [Schwarzwald]"],
  ["VOF", "Vilshofen [Niederbayern]"],
  ["VOH", "Vohenstrauß"],
  ["VS", "Schwarzwald-Baar-Kreis (Villingen-Schwenningen)"],
  ["W", "Wuppertal"],
  ["WA", "Waldeck (Korbach)"],
  ["WAF", "Warendorf"],
  ["WAK", "Wartburgkreis (Bad Salzungen, Eisenach)"],
  ["WAN", "Wanne-Eickel"],
  ["WAR", "Warburg [Westfalen]"],
  ["WAT", "Wattenscheid"],
  ["WB", "Wittenberg"],
  ["WBS", "Worbis"],
  ["WD", "Wiedenbrück"],
  ["WDA", "Werdau"],
  ["WE", "Weimar [Landkreis]"],
  ["WE", "Weimar"],
  ["WEB", "Oberwesterwaldkreis (Westerburg)"],
  ["WEG", "Wegscheid [Niederbayern]"],
  ["WEL", "Oberlahn-Kreis (Weilburg)"],
  ["WEM", "Wesermünde (Bremerhaven)"],
  ["WEN", "Weiden [Oberpfalz]"],
  ["WER", "Wertingen"],
  ["WES", "Wesel"],
  ["WF", "Wolfenbüttel"],
  ["WG", "Wangen [Allgäu]"],
  ["WHV", "Wilhelmshaven"],
  ["WI", "Wiesbaden"],
  ["WIL", "Bernkastel-Wittlich (Wittlich)"],
  ["WIS", "Wismar"],
  ["WIT", "Witten [Ruhr]"],
  ["WIZ", "Witzenhausen"],
  ["WK", "Wittstock"],
  ["WL", "Harburg (Winsen [Luhe])"],
  ["WLG", "Wolgast"],
  ["WM", "Weilheim-Schongau (Weilheim [Oberbayern])"],
  ["WMS", "Wolmirstedt"],
  ["WN", "Rems-Murr-Kreis (Waiblingen)"],
  ["WND", "St. Wendel [Saar]"],
  ["WO", "Worms"],
  ["WOB", "Wolfsburg"],
  ["WOH", "Wolfhagen [Bezirk Kassel]"],
  ["WOL", "Wolfach"],
  ["WOR", "Wolfratshausen"],
  ["WOS", "Wolfstein (Freyung [Wald])"],
  ["WR", "Wernigerode"],
  ["WRN", "Waren"],
  ["WS", "Wasserburg [Inn]"],
  ["WSF", "Weißenfels"],
  ["WST", "Ammerland (Westerstede)"],
  ["WSW", "Weißwasser"],
  ["WT", "Waldshut (Waldshut-Tiengen)"],
  ["WTL", "Wittlage (Bad Essen)"],
  ["WTM", "Wittmund"],
  ["WÜ", "Würzburg"],
  ["WUG", "Weißenburg-Gunzenhausen (Weißenburg [Bayern])"],
  ["WÜM", "Waldmünchen"],
  ["WUN", "Wunsiedel"],
  ["WUR", "Wurzen"],
  ["WW", "Westerwaldkreis (Montabaur)"],
  ["WZ", "Wetzlar"],
  ["WZL", "Wanzleben"],
  ["X", "Bundeswehr für Fahrzeuge der NATO-Hauptquartiere"],
  ["Y", "Bundeswehr"],
  ["Z", "Zoll"],
  ["Z", "Zwickau"],
  ["Z", "Zwickauer Land (Werdau)"],
  ["ZE", "Zerbst"],
  ["ZEL", "Zell [Mosel]"],
  ["ZI", "Sächsischer Oberlausitzkreis (Zittau)"],
  ["ZIG", "Ziegenhain (Schwalmstadt)"],
  ["ZP", "Zschopau"],
  ["ZR", "Zeulenroda"],
  ["ZS", "Zossen"],
  ["ZW", "Zweibrücken"],
  ["ZZ", "Zeitz"],
];

export const Data_HumanNames = {
  female: ["Annika", "Brunhilde", "Chiara", "Dora", "Emma", "Frida", "Gemma", "Hannah", "Ida", "Janine", "Karolin", "Lina", "Martha", "Nora", "Olga", "Patrizia", "Quirin", "Rebekka", "Svenja", "Tabea", "Ulrike", "Valentine", "Wiebke", "Xenia", "Yvette", "Zora"],
  male: ["Arne", "Bernd", "Carl", "Damian", "Ernst", "Friedrich", "Gustav", "Hans", "Ingolf", "Jens", "Kurt", "Lars", "Murat", "Norbert", "Olaf", "Paul", "Quentin", "Robert", "Sebastian", "Thorsten", "Ulf", "Volker", "Walther", "Xaver", "Yves", "Zoltan"],
  genders: ["agender", "androgyn", "bigender", "Burrnesha", "cisgenderfluid", "demigender", "Enbie", "Femme", "Frau", "girlfag", "guydyke", "Herr", "ilyagender", "maverique", "neurogender", "neutrois", "nibi", "pangender", "sonstig", "spiegelgender", "trans", "transfeminin", "transmaskulin", "xenogender"],
  get all() {
    return [...Data_HumanNames.female, ...Data_HumanNames.male].sort();
  },
};
