export const Data_AkademischerGrad = {
  data: {
    Bachelorgrad: {
      "B.A.": "Bachelor of Arts",
      BBA: "Bachelor of Business Administration",
      "B.Sc.": "Bachelor of Science",
      "LL.B.": "Bachelor of Laws",
      "B.Ed.": "Bachelor of Education",
      "B.Eng.": "Bachelor of Engineering",
      "B.F.A.": "Bachelor of Fine Arts",
      "B.Mus.": "Bachelor of Music",
      "B.M.A.": "Bachelor of Musical Arts",
    },
    "Mastergrade konsekutiv": {
      "M.A.": "Master of Arts",
      "M.Sc.": "Master of Science",
      "M.Eng.": "Master of Engineering",
      "LL.M.": "Master of Laws",
      "M.F.A.": "Master of Fine Arts",
      "M.Mus.": "Master of Music",
      "M.Ed.": "Master of Education",
    },
    "Mastergrade nicht konsekutiv": {
      "M.Ac.": "Master of Acoustics",
      MBA: "Master of Business Administration ",
      "MBA Eng.": "Master of Business Administration and Engineering ",
      "M.Edu": "Master of Adult Education",
      MAS: "Master of Advanced Studies in Applied Ethics",
      "M.Arch.": "Master of Architecture",
      "M.AVIMA": "Master of Aviation Management ",
      "M.BP.": "Master of Building Physics ",
      MBE: "Master of Business Engineering ",
      MBC: "International Master of Business Consulting",
      MBI: "International Master of Business Informatics",
      "M.B.L.": "Master of Business Law",
      "LL.M.oec.": "Master Wirtschaftsrecht/Business Law and Economic Law",
      MScBL: "Master of Science in Business and Law",
      MBM: "Master of Business Marketing ",
      MBR: "Master of Business Research ",
      MBS: "Master of Business Systems ",
      "M.C.L.": "Master of Comparative Law ",
      "M.Comp.Sc.": "Master of Computer Science ",
      "Master of Criminology and Police Science": "-",
      MCA: "Master of Customs Administration ",
      "Master of Economics": "Master of Economics",
      "Master of Economics and Business": "-",
      MDM: "Master in Disaster Management and Risk Governance ",
      "M.D.R.A.": "Master of Drug Regulatory Affairs",
      "Master of Engineering in Traffic Accident Research": "-",
      "M.E.S": "Master of European Studies ",
      "M.Eval.": "Master of Evaluation",
      MIM: "Master in Information Management ",
      MHA: "Master of Health Administration ",
      MHMM: "Master in Health and Medical Management",
      MHBA: "Master of Health Business Administration",
      MaHM: "Master of Hospital Management ",
      MaHE: "Master of Health Economics ",
      MoHE: "Master of Higher Education ",
      "M.I.Tax": "Master of International Taxation ",
      MALIS: "Master of Arts Library and Information Science",
      "Library and Information Science": "Master of Arts ",
      MM: "Master of Mediation ",
      "M.mel.": "Master of Medicine, Ethics and Law ",
      MoM: "Master of Organizational Management ",
      MoP: "Master of Organizational Psychology ",
      MPA: "Master of Public Administration ",
      MPH: "Master of Public Health",
      MPM: "Master of Public Management ",
      MPP: "Master of Public Policy",
      "Master in Redevelopment": "-",
      MScHM: "Master of Science in Heritage Management",
      MSM: "Master of Social Management ",
      MTM: "Master of Technology Management ",
      "M.Th.": "Master of Theology",
    },
    Lizenziat: {
      "lic.theol.": "Lizenziat der Theologie",
      "lic.iur.can.": "Lizenziat des (kanonischen) Kirchenrechts",
      "lic.rer.publ.": "Lizenziat der Publizistik",
      "lic.rer.reg.": "Lizenziat der Regionalwissenschaft",
    },
    Bakkalaureusgrad: {
      "B.A.": "Bakkalaureus Artium bzw. Baccalaureus Artium",
      "Bac.Jur.": "Bakkalaureus Juris bzw. Baccalaureus Juris",
      "Bac.Oec.": "Bakkalaureus Oeconomicus bzw. Baccalaureus Oeconomicus",
    },
    Magistergrad: {
      "M.A.": "Magister Artium",
      "M.Sc.": "Magister Scientiarum",
      "LL.M.": "Legum Magister",
      MLE: "Magister Legum Europae",
      "Mag.rer.publ.": "Magister rerum publicarum",
      "Mag.theol. bzw. M.Theol.": "Magister Theologiae",
      "Mag.iur.": "Magister iuris",
      "M.Th.": "Magister Theologiae",
    },
    Diplomgrad_FH: {
      "Dipl.-Agrar Ing. (FH)": "Diplom-Agraringenieur (FH)",
      "Dipl.-Archivar (FH)": "Diplom-Archivar (FH)",
      "Dipl.-Betriebsw. (FH)": "Diplom-Betriebswirt (FH)",
      "Dipl.-Bibl. (FH)": "Diplom-Bibliothekar (FH)",
      "Dipl.-Bioinf. (FH)": "Diplom-Bioinformatiker (FH)",
      "Dipl.-Bioing. (FH)": "Diplom-Bioingenieur (FH)",
      "Dipl.-Biomath. (FH)": "Diplom-Biomathematiker (FH)",
      "Dipl.-Chem. (FH)": "Diplom-Chemiker (FH)",
      "Dipl.-Des. (FH)": "Diplom-Designer (FH)",
      "Dipl.-Dok. (FH)": "Diplom-Dokumentar (FH)",
      "Dipl.-Dolm. (FH)": "Diplom-Dolmetscher (FH)",
      "Dipl.-Energiewirt (FH)": "Diplom-Energiewirt (FH)",
      "Dipl.-Ergotherapeut (FH)": "Diplom-Ergotherapeut (FH)",
      "Dipl.-oec.-troph. (FH)": "Diplom-Oecotrophologe (FH)",
      "Dipl.-Fachübersetzer (FH)": "Diplom-Fachübersetzer (FH)",
      "Dipl.-Finw. (FH)": "Diplom-Finanzwirt (FH)",
      "Dipl.-Forsting. (FH)": "Diplom-Forstingenieur (FH)",
      "Dipl. FÖ (FH)": "Diplom-Fitnessökonom (FH)",
      "Dipl.-Freizeitwiss. (FH)": "Diplom-Freizeitwissenschaftler (FH)",
      "Dipl.-Ges.oec. (FH)": "Diplom-Gesundheitsökonom (FH)",
      "Dipl.-Immobilienw. (FH)": "Diplom-Immobilienwirt (FH)",
      "Dipl.-Inf.(FH)": "Diplom-Informatiker (FH)",
      "Dipl.-Inf.-Wirt (FH)": "Diplom-Informationswirt (FH)",
      "Dipl.-Ing. (FH)": "Diplom-Ingenieur (FH)",
      "Dipl.-Ing.Gartenbau (FH)": "Diplom-Gartenbauingenieur (FH)",
      "Dipl.-Journ. (FH)": "Diplom-Journalist (FH)",
      "Dipl.-Kffr. (FH)": "Diplom-Kauffrau (FH)",
      "Dipl.-Kfm. (FH)": "Diplom-Kaufmann (FH)",
      "Dipl.-Komm.Psych. (FH)": "Diplom-Kommunikationspsychologe (FH)",
      "Dipl.-Kult.arb. (FH)": "Diplom-Kulturarbeiter (FH).[22]",
      "Dipl.-Künstler (FH)": "Diplom-Künstler (FH)",
      "Dipl.-Kunsttherap. (FH)": "Diplom-Kunsttherapeut (FH)",
      "Dipl.-Logist. (FH)": "Diplom-Logistiker (FH)",
      "Dipl.-Math. (FH)": "Diplom-Mathematiker (FH)",
      "Dipl.-Medieninform. (FH)": "Diplom-Medieninformatiker (FH)",
      "Dipl.-Medienök. (FH)": "Diplom-Medienökonom (FH)",
      "Dipl.-Medienw. (FH)": "Diplom-Medienwirt (FH)",
      "Dipl.-Mediator (FH)": "Diplom-Mediator (FH)",
      "Dipl.-Museol. (FH)": "Diplom-Museologe (FH)",
      "Dipl.-Musiktherap. (FH)": "Diplom-Musiktherapeut/in (FH)",
      "Dipl.-Naut. (FH)": "Diplom-Nautiker (FH)",
      "Dipl.oec.troph (FH)": "Diplom-Ökotrophologe (FH)",
      "Dipl.-Online-Journalist (FH)": "Diplom-Online-Journalist (FH)",
      "Dipl.-Pfl. (FH)": "Diplom-Pfleger (FH)",
      "Dipl.-Pflegew. (FH)": "Diplom-Pflegewirt (FH)",
      "Dipl.-Pflegepäd. (FH)": "Diplom-Pflegepädagoge (FH)",
      "Dipl.-Physiotherapeut (FH)": "Diplom-Physiotherapeut (FH)",
      "Dipl.-Pol. (FH)": "Diplom-Politologe (FH)",
      "Dipl.-Red. (FH)": "Diplom-Redakteur (FH)",
      "Dipl.-Rel.-päd. (FH)": "Diplom-Religionspädagoge (FH)",
      "Dipl.-Rest. (FH)": "Diplom-Restaurator (FH)",
      "Dipl.-Reha-psych. (FH)": "Diplom-Rehabilitationspsychologe (FH)",
      "Dipl.-Rpfl. (FH)": "Diplom-Rechtspfleger (FH)",
      "Dipl.-Sicherheitsing. (FH)": "Diplom-Sicherheitsingenieur (FH)",
      "Dipl.-Soz. Arb. (FH)": "Diplom-Sozialarbeiter (FH)",
      "Dipl.-Soz.jur. (FH)": "Diplom-Sozialjurist (FH)",
      "Dipl.-Soz.päd. (FH)": "Diplom-Sozialpädagoge (FH)",
      "Dipl.-Soz.-wirt (FH)": "Diplom-Sozialwirt (FH)",
      "Dipl.-Techn. (FH)": "Diplom-Technologe (FH)",
      "Dipl.-Tech.-Red. (FH)": "Diplom-Technik-Redakteur (FH)",
      "Dipl.-Übers. (FH)": "Diplom-Übersetzer (FH)",
      "Dipl.-Vers.-Betriebsw. (FH)": "Diplom-Versicherungsbetriebswirt (FH)",
      "Dipl.-Verww. (FH)": "Diplom-Verwaltungswirt (FH)",
      "Dipl.-Verw.-Betriebsw. (FH)": "Diplom-Verwaltungsbetriebswirt (FH)",
      "Dipl.-Verw.-Manager (FH)": "Diplom-Verwaltungsmanager (FH)",
      "Dipl.-Volksw. (FH)": "Diplom-Volkswirt (FH)",
      "Dipl.-Wirt.-Inf. (FH)": "Diplom-Wirtschaftsinformatiker (FH)",
      "Dipl.-Wi.-Inform. (FH)": "Diplom-Wirtschaftsinformatiker (FH)",
      "Dipl.-Wirtsch.-Ing. (FH)": "Diplom-Wirtschaftsingenieur (FH)",
      "Dipl.-Wirt.-Ing. (FH)": "Diplom-Wirtschaftsingenieur (FH)",
      "Dipl.-Wi.Jur. (FH)": "Diplom-Wirtschaftsjurist (FH)",
      "Dipl.-Wirtschaftspsych. (FH)": "Diplom-Wirtschaftspsychologe (FH)",
      "Dipl.-Wirt.-Übers.(FH)": "Diplom-Wirtschaftsübersetzer (FH) ",
      "Dipl.-Inf. (DH)": "Diplom-Informatiker (Duale Hochschule)",
      "Dipl.-Ing. (DH)": "Diplom-Ingenieur (Duale Hochschule)",
      "Dipl.-Betriebsw. (DH)": "Diplom-Betriebswirt (Duale Hochschule)",
      "Dipl.-Wirtsch.-Inf. (DH)": "Diplom-Wirtschaftsinformatiker (Duale Hochschule)",
      "Dipl.-Soz.päd. (DH)": "Diplom-Sozialpädagoge (Duale Hochschule)",
      "Dipl.-Anim.": "Diplom-Animator",
      "Dipl.-Arch.": "Diplom-Architekt (DDR-Grad, wird nicht mehr vergeben)",
      "Dipl.-Audiovisuelle Medien": "Diplom in audiovisuellen Medien",
      "Dipl.-Des.": "Diplom-Designer",
      "Dipl.-Film- u. Fernsehdram.": "Diplom-Film- und Fernsehdramaturg",
      "Dipl.-Film- u. Fernsehwirt.": "Diplom-Film- und Fernsehwirtschaftler",
      "Dipl.-Filmkomp.": "Diplom-Filmkomponist",
      "Dipl.-Freie Kunst": "Diplom für Freie Kunst",
      "Dipl.-Ing.": "Diplom-Ingenieur",
      "Dipl.-Kam.": "Diplom-Kameramann",
      "Dipl.-Kunstpädagogik": "Diplom für Bildende Kunst und Pädagogik",
      "Dipl.-Kunstpädagogik/Kunstvermittlung": "Diplom in Kunstpädagogik/Kunstvermittlung",
      "Dipl.-Kunst.-Päd.": "Diplom-Kunstpädagoge",
      "Dipl.-Rest.": "Diplom-Restaurator",
      "Dipl. Mus.": "Diplom in Musik",
      "Dipl.-Mus.-Päd.": "Diplom-Musikpädagoge",
      "Dipl.-Musikl.": "Diplom-Musiklehrer",
      "Dipl.-Reg.": "Diplom-Regisseur (auch Musiktheaterregisseur)",
      "Dipl.-Schau.": "Diplom-Schauspieler",
      "Dipl.-Schnittm.": "Diplom-Schnittmeister",
      "Dipl.-Szeneb.": "Diplom-Szenebildner",
      "Dipl.-Szenem.": "Diplom-Szenemeister",
      "Dipl.-Tonm.": "Diplom-Tonmeister",
      "Dipl. Vis. Komm.": "Diplom für Visuelle Kommunikation",
    },
    Diplomgrad_Uni: {
      "Dipl.agr.biol.": "Diplom-Agrarbiologe",
      "Dipl.agr.oec.": "Diplom-Agrarökonom",
      "Dipl.-Angl.": "Diplom-Anglist",
      "Dipl.-Arch.": "Diplom-Architekt",
      "Dipl.-Berufspäd.": "Diplom-Berufspädagoge",
      "Dipl.-Betriebsw.": "Diplom-Betriebswirt",
      "Dipl.-Bibl.": "Diplom-Bibliothekar",
      "Dipl.-Biochem.": "Diplom-Biochemiker",
      "Dipl.-Biogeogr.": "Diplom-Biogeograph",
      "Dipl.-Bioinf.": "Diplom-Bioinformatiker",
      "Dipl.-Biol.": "Diplom-Biologe",
      "Dipl.-Biol. (t.o.)": "Diplom-Biologe",
      "Dipl.-Biophys.": "Diplom-Biophysiker",
      "Dipl.-Biotechnol.": "Diplom-Biotechnologie",
      "Dipl.-Braumeister": "Diplom-Braumeister",
      "Dipl.-Chem.": "Diplom-Chemiker",
      "Dipl.-Chem.-Ing.": "Diplom-Chemieingenieur",
      "Dipl.-Chem.oec.": "Diplom-Wirtschaftschemiker",
      "Dipl.-Comp.-Math.": "Diplom-Computermathematiker/-in",
      "Dipl.-Demogr.": "Diplom-Demograph",
      "Dipl.-Des.": "Diplom-Designer",
      "Dipl.-Dolm.": "Diplom-Dolmetscher",
      "Dipl.-Dram.": "Diplom-Dramaturg",
      "Dipl.-Forstw.": "Diplom-Forstwirt",
      "Dipl.-Geogr.": "Diplom-Geograph",
      "Dipl.-Geoinf.": "Diplom-Geoinformatiker",
      "Dipl.-Geol.": "Diplom-Geologe",
      "Dipl.-Geoökol.": "Diplom-Geoökologe",
      "Dipl.-Geophys.": "Diplom-Geophysiker",
      "Dipl.-Germ.": "Diplom-Germanist",
      "Dipl.-Geront.": "Diplom-Gerontologe",
      "Dipl.-Ges.oec.": "Diplom-Gesundheitsökonom",
      "Dipl.-Ghl.": "Diplom-Gesundheitslehrer",
      "Dipl. GDFS": "Diplom für Grenzüberschreitende deutsch-französische Studien",
      "Dipl.-Gwl.": "Diplom-Gewerbelehrer",
      "Dipl.-Gyml.": "Diplom-Gymnasiallehrer",
      "Dipl.-Hdl.": "Diplom-Handelslehrer",
      "Dipl.-Heilpäd.": "Diplom-Heilpädagoge",
      "Dipl.-Hist.": "Diplom-Historiker",
      "Dipl.-Holzwirt": "Diplom-Holzwirt",
      "Dipl.-Humanbiologe": "Diplom-Humanbiologe",
      "Dipl. human. biol.": "Diplom-Humanbiologe",
      "Dipl.-Hydrol.": "Diplom-Hydrologe",
      "Dipl.-Ind. Arch.": "Diplom-Industriearchäologe",
      "Dipl.-Inf. oder Dipl.-Inform.": "Diplom-Informatiker",
      "Dipl.-Inform. Med.": "Diplom-Informatiker der Medizin",
      "Dipl.-Inf.Wirt/Inform.Wirt": "Diplom-Informationswirt",
      "Dipl.-Inf.wiss": "Diplom-Informationswissenschaftler",
      "Dipl.-Ing.": "Diplom-Ingenieur",
      "Dipl.-Ing. agr.": "Diplom-Agraringenieur",
      "Dipl.-Ing.-Inf.": "Diplom-Ingenieurinformatiker",
      "Dipl.-Ing. oec.": "Diplom-Ingenieur-Ökonom Wirtschaftsingenieur",
      "Dipl.-Ing.-Päd.": "Diplom-Ingenieur-Pädagoge",
      "Dipl.-Ing. silv.": "Diplom-Forstingenieur",
      "Dipl.-jur. oder Dipl.-Jur.": "Diplom-Jurist",
      "Dipl.-Journ.": "Diplom-Journalist",
      "Dipl.-Kff.": "Diplom-Kauffrau",
      "Dipl.-Kfm.": "Diplom-Kaufmann",
      "Dipl.-Kfm. t.o.": "Diplom-Kaufmann technisch orientiert",
      "Dipl.-Komm.-Wirt": "Diplom-Kommunikationswirt",
      "Dipl.-Krim.": "Diplom-Kriminalist",
      "Dipl.-Kult.": "Diplom-Kulturwissenschaftler",
      "Dipl.-Kult.Päd.": "Diplom-Kulturpädagoge",
      "Dipl.-Kult.Man.": "Diplom-Kulturmanager",
      "Dipl.-Kulturwirt": "Diplom-KulturwirtIn",
      "Dipl.-Künstler": "Diplom-Künstler",
      "Dipl.-Kunstpädagoge": "Diplom-Kunstpädagoge",
      "Dipl.-Landsch.-ökol.": "Diplom-Landschaftsökologe",
      "Dipl.-Lebensmittelchem.": "Diplom-Lebensmittelchemiker",
      "Dipl.-Lehrer": "Diplom-Lehrer",
      "Dipl.-Ling.": "Diplom-Linguist",
      "Dipl.-LMChem.": "Diplom-Lebensmittelchemiker",
      "Dipl.-LM-Ing.": "Diplom-Lebensmittelingenieur",
      "Dipl.-Logist.": "Diplom-Logistiker",
      "Dipl.-Math.": "Diplom-Mathematiker",
      "Dipl.-Math. oec.": "Diplom-Wirtschaftsmathematiker",
      "Dipl.-Wi.-Math.": "Diplom-Finanz- und Wirtschaftsmathematiker",
      "Dipl.-Math. techn.": "Diplom-Technomathematiker",
      "Dipl.-Med.": "Diplom-Mediziner",
      "Dipl.-Vet.-Med.": "Diplom-Veterinärmediziner",
      "Dipl.-Med. Päd.": "Diplommedizinpädagoge",
      "Dipl.-Medienberater": "Diplom-Medienberater",
      "Dipl.-Mediengestalter": "Diplom-Mediengestalter",
      "Dipl.-Medieninf.": "Diplom-Medieninformatiker",
      "Dipl.-Medienprakt.": "Diplom-Medienpraktiker",
      "Dipl.-Medienwirt": "Diplom-Medienwirt",
      "Dipl.-Medienwiss.": "Diplom-Medienwissenschaftler",
      "Dipl.-Met.": "Diplom-Meteorologe",
      "Dipl.-Mot.": "Diplom-Motologe",
      "Dipl.-Mol.Med.": "Diplom-Molekularmediziner",
      "Dipl.-Mikrobiol.": "Diplom-Mikrobiologe",
      "Dipl.-Mil.": "Diplom-Militärwissenschaftler",
      "Dipl.-Min.": "Diplom-Mineraloge",
      "Dipl.-NanoSc.": "Diplom-Nanostrukturwissenschaftler",
      "Dipl.-Nat.": "Diplom-Naturwissenschaftler",
      "Dipl.-Hist.Sc": "Diplom-Naturwissenschaftshistoriker",
      "Dipl.-Neurowiss.": "Diplom-Neurowissenschaftler",
      "Dipl.oec.troph.": "Diplom-Ökotrophologe",
      "Dipl.-Oec.": "Diplom-Ökonom",
      "Dipl.-Ök.": "Diplom-Ökonom",
      "Dipl.-oen.": "Diplom-Oenologe",
      "Dipl.-Orient.": "Diplom-Orientalist",
      "Dipl.-Orientarchäologe": "Diplom-Orientarchäologe",
      "Dipl.-Oz.": "Diplom-Ozeanograph",
      "Dipl.-Päd.": "Diplom-Pädagoge",
      "Dipl.-PGW": "Diplom-Pflege- und Gesundheitswissenschaftler",
      "Dipl.-Pharm.": "Diplom-Pharmazeut",
      "Dipl.-Phil.": "Diplom-Philosoph",
      "Dipl.-Phys.": "Diplom-Physiker",
      "Dipl.-Phys. (Med.)": "Diplom-Medizinphysiker",
      "Dipl.-Phys.Ing.": "Diplom-Physikingenieur",
      "Dipl.-Phys. oec.": "Diplom-Wirtschaftsphysiker",
      "Dipl.-Pol.": "Diplom-Politologe",
      "Dipl.-Prähist.": "Diplom-Prähistoriker",
      "Dipl.-Psych.": "Diplom-Psychologe",
      "Dipl.-Reg.-Wiss.": "Diplom-Regionalwissenschaftler",
      "Dipl.-Reh.-Päd.": "Diplom-Rehabilitationspädagoge",
      "Dipl. rer. com.": "Diplom-Kommunikationswissenschaftler",
      "Dipl. rer. oec.": "Diplom-Wirtschaftswissenschaftler",
      "Dipl. rer. pol.": "Diplomatus rerum politicarum",
      "Dipl.-Rom.": "Diplom-Romanist",
      "Dipl. sc. pol. Univ.": "Diplomaticus scientiae politicae Universitatis",
      "Dipl.-Sicherheits.-Ing.": "Diplom-Sicherheitsingenieur",
      "Dipl.-Soz.Ök.": "Diplom-Sozialökonom",
      "Dipl.-Soz.": "Diplom-Soziologe",
      "Dipl.-Soz. tech.": "Diplom-Soziologe technikwissenschaftlicher Richtung",
      "Dipl.-Soz.päd.": "Diplom-Sozialpädagoge",
      "Dipl.-Sozw.": "Diplom-Sozialwirt",
      "Dipl.-Sozialw.": "Diplom-Sozialwissenschaftler",
      "Dipl.-Sporting.": "Diplom-Sportingenieur",
      "Dipl.-Sportl.": "Diplom-Sportlehrer",
      "Dipl.-SpOec.": "Diplom-Sportökonom",
      "Dipl.-Sportwiss.": "Diplom-Sportwissenschaftler",
      "Dipl.-Sprachm.": "Diplom-Sprachmittler",
      "Dipl.-Sprechwiss.": "Diplom-Sprechwissenschaftler",
      "Dipl.-Staatsw.": "Diplom-Staatswissenschaftler",
      "Dipl.-Stat.": "Diplom-Statistiker",
      "Dipl.-Stom.": "Diplom-Zahnarzt",
      "Dipl.-Stomat.": "Diplom-Zahnarzt",
      "Dipl.-Systemwiss.": "Diplom-Systemwissenschaftler",
      "Dipl.-Tech. Math.": "Diplom-Technomathematiker",
      "Dipl.-Technoinform.": "Diplom-Technoinformatiker",
      "Dipl.-Theol.": "Diplom-Theologe",
      "Dipl.-Troph.": "Diplom-Trophologe",
      "Dipl.-Übersetzer": "Diplom-Übersetzer",
      "Dipl.-Umweltwiss.": "Diplom-Umweltwissenschaftler",
      "Dipl.-UWT": "Diplom-Umwelttechniker",
      "Dipl.-Verk.wirtsch.": "Diplom-Verkehrswirtschaftler",
      "Dipl.-Verw. Wiss.": "Diplom-Verwaltungswissenschaftler",
      "Dipl.-Volksw.": "Diplom-Volkswirt",
      "Dipl.-Wirt.": "Diplom-Wirtschaftler",
      "Dipl.-Wirtchem.": "Diplom-Wirtschaftschemiker",
      "Dipl.-Wirt.-Inf.": "Diplom-Wirtschaftsinformatiker",
      "Dipl.-Wi.-Ing.": "Diplom-Wirtschaftsingenieur",
      "Dipl. iur .oec. univ.": "Diplom-Wirtschaftsjurist Univ.",
      "Dipl.-Wigeo.": "Diplom-Wirtschaftsgeograph",
      "Dipl.-Wirtl.": "Diplom-Wirtschaftslehrer",
      "Dipl.-Wipäd.": "Diplom-Wirtschaftspädagoge",
      "Dipl.-Wiss.org.": "Diplom-Wissenschaftsorganisator",
      "Dipl.-WiWi.": "Diplom-Wirtschaftswissenschaftler",
    },
    Doktorgrad: {
      "Dr.agr. (agriculturae)": "Doktor der Agrarwissenschaft",
      "Dr.B.A. (D.B.A.)": "Doctor of Business Administration",
      "Dr.biol.anim. (biologiae animalis)": "Doktor der Tierphysiologie",
      "Dr.biol.hom. (biologiae hominis)": "Doktor der Humanbiologie",
      "Dr.cult. (culturae)": "Doktor der Kulturwissenschaften",
      "Dr.disc.pol. (disciplinarum politicarum)": "Doktor der Sozialwissenschaften",
      "Dr.-Ing.(Doktoringenieur)": "Doktor der Ingenieurwissenschaften",
      "Dr.iur. (iuris)": "Doktor der Rechte bzw. Doktor des Rechts/der Rechtswissenschaft",
      "Dr.iur.can. (iuris canonici)": "Doktor der kanonischen Rechtswissenschaften",
      "Dr.iur. et rer.pol. (iuris et rerum politicarum)": "Doktor der Rechts- und Staatswissenschaften",
      "Dr.iur.utr. (iuris utriusque)": "Doktor beider Rechte",
      "Dr.math. (mathematicae)": "Doktor der Mathematik",
      "Dr.med. (medicinae)": "Doktor der Medizin",
      "Dr.med.dent. (medicinae dentariae)": "Doktor der Zahnheilkunde/Zahnmedizin",
      "Dr.med.sci.": "Doktor der Medizinischen Wissenschaft",
      "Dr.med.vet. (medicinae veterinariae)": "Doktor der Tiermedizin",
      "Dr.nat.med.": "Doktor der naturwissenschaftlichen Medizin",
      "Dr.nat.techn. (naturalium technicarum)": "Doktor der Bodenkultur",
      "Dr.oec. (oeconomiae)": "Doktor der Wirtschafts-/Verwaltungswissenschaften",
      "Dr.oec.publ. (oeconomiae publicae)": "Doktor der Staatswissenschaften/Volkswirtschaft",
      "Dr.oec.troph. (oecotrophologiae)": "Doktor der Ernährungswissenschaften/Haushaltswissenschaft",
      "Dr.paed. (paedagogiae)": "Doktor der Erziehungswissenschaften",
      "Dr.pharm. (pharmaciae)": "Doktor der Pharmazie",
      "Dr.phil. (philosophiae)": "Doktor der Philosophie",
      "Dr.phil. in art. (philosophiae in artibus)": "Doktor der Philosophie in den Künsten (künstlerisch-wissenschaftlich)",
      "Dr.phil.nat. (philosophiae naturalis)": "Doktor der Naturwissenschaften",
      "Dr.PH (public health)": "Doktor der Public Health",
      "Dr.rer.agr. (rerum agriculturarum)": "Doktor der Landbauwissenschaften",
      "Dr.rer.biol.hum. (rerum biologiae humanae)": "Doktor der Humanbiologie",
      "Dr.rer.biol.vet. (rerum biologiae veterinariae)": "Doktor der Veterinärbiologie",
      "Dr.rer.cult. (rerum culturarum)": "Doktor der Kulturwissenschaften",
      "Dr.rer.cur. (rerum curae)": "Doktor der Pflegewissenschaften",
      "Dr.rer.forest. (rerum forestalium)": "Doktor der Forstwissenschaften",
      "Dr.rer.hort. (rerum horticulturarum)": "Doktor der Gartenbauwissenschaften",
      "Dr.rer.hum. (rerum humanarum)": "Doktor der Medizinwissenschaften",
      "Dr.rer.med. (rerum medicarum)": "Doktor der Medizinwissenschaften",
      "Dr.rer.medic. (rerum medicinalium)": "Doktor der theoretischen Medizin, Medizinwissenschaften, Biomedizin, Medizintechnologie, medizinischen Biometrie und Bioinformatik, Gesundheitswissenschaften",
      "Dr.rer.merc. (rerum mercantilium)": "Doktor der Handelswissenschaften",
      "Dr.rer.mont. (rerum montanarum)": "Doktor der Bergbauwissenschaften",
      "Dr.rer.nat. (rerum naturalium)": "Doktor der Naturwissenschaften",
      "Dr.rer.oec. (rerum oeconomicarum)": "Doktor der Wirtschaftswissenschaften",
      "Dr.rer.physiol. (rerum physiologicarum)": "Doktor der Humanbiologie",
      "Dr.rer.pol. (rerum politicarum)": "Sammelbegriff für Doktoren der Politikwissenschaft, Sozialwissenschaften, Staatswissenschaften oder Wirtschaftswissenschaften",
      "Dr.rer.publ. (rerum publicarum)": "Doktor der Verwaltungswissenschaften",
      "Dr.rer.sec. (rerum securitatis)": "Doktor der Sicherheitswissenschaften",
      "Dr.rer.silv. (rerum silvestrium bzw. rerum silvaticarum)": "Doktor der Forstwissenschaften",
      "Dr.rer.soc. (rerum socialium)": "Doktor der Sozialwissenschaften",
      "Dr.rer.tech. (rerum technicarium)": "Doktor der Technischen Wissenschaften",
      "Dr.sc.agr. (scientiarum agrarium)": "Doktor der Agrarwissenschaften",
      "Dr.sc.hum. (scientiarum humanarum)": "Doktor der Humanwissenschaften",
      "Dr.sc.mus. (scientiae musicae)": "Doktor der Musikwissenschaften",
      "Dr.sc.oec. (scientiarum oeconomicarum)": "Doktor der Wirtschaftswissenschaften",
      "Dr.sc.phil. (scientiarum philosophiae)": "Doktor der Philosophiewissenschaften",
      "Dr.sc.pol. (scientiarum politicarum)": "Doktor der Wirtschafts- und Sozialwissenschaften",
      "Dr.sc.soc. (scientiae socialis)": "Doktor der Sozialwissenschaften",
      "Dr.sc.techn. (scientiarum technicarum)": "Doktor der technischen Wissenschaften",
      "Dr.Sportwiss.": "Doktor der Sportwissenschaften",
      "Dr.theol. (theologiae)": "Doktor der Theologie",
      "Dr.troph. (trophologiae)": "Doktor der Ernährungswissenschaft",
      "Ph.D. Freie Kunst": "Doktorgrad für Graduierte aus den Künsten (Bauhaus-Universität Weimar)",
      "Ph.D. Kunst und Design": "Doktorgrad für Graduierte aus dem Design (Bauhaus-Universität Weimar)",
      "Ph.D. Medienkunst": "Doktorgrad für Graduierte aus der Medienkunst (Bauhaus-Universität Weimar)",
      "Dr.h.c. (honoris causa)": "Ehrendoktor",
      "Dr.e.h. (ehrenhalber)": "Ehrendoktor",
      "D. (ehrenhalber)": "Ehrendoktor der ev. Theologie",
    },
  },
  get allGrades() {
    return Object.keys(Data_AkademischerGrad.data);
  },
  get allEntries() {
    let data = {};
    for (let k in Data_AkademischerGrad.data) {
      data = {
        ...data,
        ...Data_AkademischerGrad.data[k],
      };
    }
    return data;
  },
};
